"""Crucible application layer: use cases and ports.

Boundary rule (ADR-001, enforced by import-linter): may import crucible.domain
and the standard library only. Concrete adapters (SQLAlchemy, Redis, S3, model
providers) are injected by the composing app.
"""

from crucible.application.commands.api_keys import (
    CreateApiKey,
    CreateApiKeyInput,
    CreatedApiKey,
    RevokeApiKey,
)
from crucible.application.commands.budget import (
    GetBudgetStatus,
    SetBudget,
)
from crucible.application.commands.datasets import (
    CompleteDatasetUpload,
    CompleteUploadInput,
    CreateDatasetDownloadUrl,
    StartDatasetUpload,
    StartUploadInput,
    StartUploadResult,
)
from crucible.application.commands.online import (
    ONLINE_EVALUATOR_VERSION,
    OnlineSampleSummary,
    RunOnlineChecks,
)
from crucible.application.commands.retention import (
    DEFAULT_RETENTION_DAYS,
    ApplyRetention,
    RetentionOutcome,
)
from crucible.application.commands.reviews import (
    REVIEW_RUBRIC_VERSION,
    ClaimReview,
    ListReviewQueue,
    RubricGrades,
    SubmitReview,
)
from crucible.application.commands.runs import (
    RUN_COST_ESTIMATE_USD,
    CancelRun,
    CreateRun,
    CreateRunInput,
    ResolveRunReview,
    request_hash,
)
from crucible.application.ports import (
    AgentAttemptRecord,
    ApiKeyRecord,
    AuditEntry,
    AuditSink,
    BudgetRepository,
    BudgetStatus,
    CacheEntryRecord,
    CacheStats,
    CacheStore,
    Clock,
    DatasetRecord,
    DatasetRepository,
    DatasetVersionRecord,
    HealthProbe,
    IdentityRepository,
    JobQueue,
    MembershipRecord,
    MetricsRepository,
    ObjectStore,
    OrganizationRecord,
    RateLimiter,
    RetentionRepository,
    ReviewQueueItem,
    ReviewRecord,
    ReviewRepository,
    RunEventRecord,
    RunRecord,
    RunRepository,
    RunTelemetryRow,
    ScoreInput,
    ScoreRecord,
    ScoreStore,
    UserRecord,
)
from crucible.application.queries.reads import (
    AttemptReader,
    GetCacheStats,
    GetDatasetVersion,
    GetRun,
    GetRunTelemetry,
    ListApiKeys,
    ListDatasets,
    ListDatasetVersions,
    ListRunAttempts,
    ListRunEvents,
    ListRuns,
    ListScores,
)
from crucible.application.queries.system_status import GetSystemStatus
from crucible.application.services.authenticate import (
    ResolveApiKeyPrincipal,
    ResolveUserPrincipal,
    VerifiedIdentity,
)

__all__ = [
    "DEFAULT_RETENTION_DAYS",
    "ONLINE_EVALUATOR_VERSION",
    "REVIEW_RUBRIC_VERSION",
    "RUN_COST_ESTIMATE_USD",
    "AgentAttemptRecord",
    "ApiKeyRecord",
    "ApplyRetention",
    "AttemptReader",
    "AuditEntry",
    "AuditSink",
    "BudgetRepository",
    "BudgetStatus",
    "CacheEntryRecord",
    "CacheStats",
    "CacheStore",
    "CancelRun",
    "ClaimReview",
    "Clock",
    "CompleteDatasetUpload",
    "CompleteUploadInput",
    "CreateApiKey",
    "CreateApiKeyInput",
    "CreateDatasetDownloadUrl",
    "CreateRun",
    "CreateRunInput",
    "CreatedApiKey",
    "DatasetRecord",
    "DatasetRepository",
    "DatasetVersionRecord",
    "GetBudgetStatus",
    "GetCacheStats",
    "GetDatasetVersion",
    "GetRun",
    "GetRunTelemetry",
    "GetSystemStatus",
    "HealthProbe",
    "IdentityRepository",
    "JobQueue",
    "ListApiKeys",
    "ListDatasetVersions",
    "ListDatasets",
    "ListReviewQueue",
    "ListRunAttempts",
    "ListRunEvents",
    "ListRuns",
    "ListScores",
    "MembershipRecord",
    "MetricsRepository",
    "ObjectStore",
    "OnlineSampleSummary",
    "OrganizationRecord",
    "RateLimiter",
    "ResolveApiKeyPrincipal",
    "ResolveRunReview",
    "ResolveUserPrincipal",
    "RetentionOutcome",
    "RetentionRepository",
    "ReviewQueueItem",
    "ReviewRecord",
    "ReviewRepository",
    "RevokeApiKey",
    "RubricGrades",
    "RunEventRecord",
    "RunOnlineChecks",
    "RunRecord",
    "RunRepository",
    "RunTelemetryRow",
    "ScoreInput",
    "ScoreRecord",
    "ScoreStore",
    "SetBudget",
    "StartDatasetUpload",
    "StartUploadInput",
    "StartUploadResult",
    "SubmitReview",
    "UserRecord",
    "VerifiedIdentity",
    "request_hash",
]
